# PromptDev configuration with full promptfoo compatibility

description: "Calendar event summary evaluation - promptfoo compatible"

prompts:
  - file://./prompt.yaml

providers:
  - id: "ollama_llama_3_2"
    model: "ollama:llama3.2:3b-instruct-q8_0"
    config:
      temperature: 0.0
      base_url: "http://localhost:11434/v1"
  - id: "ollama_gemma3"
    model: "ollama:gemma3"
    config:
      temperature: 0.0
      base_url: "http://localhost:11434/v1"

defaultTest:
  options:
    provider: "pydantic-ai:together-deepseek"
  assert:
    # Promptfoo llm-rubric evaluator (commented out in original)
    # - type: llm-rubric
    #   value: does not describe self as an AI, model, or chatbot
    - $ref: '#/assertionTemplates/assertExpected'
    - $ref: '#/assertionTemplates/containsValidJSONSchema'
    # Promptfoo g-eval evaluator (commented out in original)  
    # - type: g-eval
    #   value: 'Ensure the response is factually accurate and well-structured'
    #   threshold: 0.7

tests:
  - file: "file://./calendar_events_dataset.jsonl"

assertionTemplates:
  containsValidJSONSchema:
    type: contains-json  # Promptfoo evaluator type
    value:
      $ref: '#/calendarEventSummarySchema'
  assertExpected:
    metric: assertExpected
    type: python  # Promptfoo compatible python evaluator
    value: file://./assert.py

# Direct schema definition (promptfoo style)
calendarEventSummarySchema:
  properties:
    out_of_office:
      description: 'Whether the event is an out of office event'
      title: 'Out of office'
      type: 'boolean'
    name:
      description: 'The name of the person who is out of office'
      title: 'Name'
      type: 'string'
    event_type:
      description: 'The type of the event'
      title: 'Event type'
      type: 'string'
  required:
    - 'out_of_office'
    - 'name'
    - 'event_type'
  title: 'Calendar event summary'
  type: 'object'
